application: tic-tac-toe-you-can-never-win
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: server.api.application
  secure: always

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
