#!/usr/bin/env python
"""
The Main Game of Unbeatable Tic-Tac-Toe

To run the tests 

    %python -m unittest test

To run the game from the command line

First make sure the file is executable
    % chmod +x Tic-Tac-Toe

Then run the game
    % Tic-Tac-Toe

Enjoy!
"""
import Board
import Brain


class Game(object):

    def __init__(self):

        self.board = None
        self.current_player = None

    def main(self):
        """Run the game"""

        self._set_board()
        self._print_message('Welcome to Tic Tac Toe!')
        while True:
            self.board.inputPlayerLetter()
            self._print_message('The %s will go first.' % self.current_player)
            self.play()
            again = self.board.playAgain()
            if again:
                self._set_board()
                continue
            break
        self._print_message("Ok, I'll go play a nice game of global thermonuclear war.")

    def play(self):
        """Here is where we play the game"""

        turn = self.board.firstMove()
        while True:
            if self.current_player == 'player':
                # Player's turn.
                game_over = self._player_move()
            else:
                # Computer's turn. Give it Tabla Rasa
                game_over = self._computer_move()
            if game_over is True:
                return
            self._toggle_turn()

    def _set_board(self):
        self.board = Board.Board()
        self.current_player = self.board.firstMove()

    def _toggle_turn(self):
        """switch the player"""
        if self.current_player == 'computer':
            self.current_player = 'player'
        else:
            self.current_player = 'computer'

    def _player_move(self):
        """Do the player move"""
        self.board.getPlayerMove()
        outcome = self.board.isWinner()
        if outcome == 'win':
        #We will never get here BUT just in case
            self._print_message('Hooray! You have won the game!')
            return True
        elif outcome == 'draw':
            self._print_message('The game is a tie!')
            return True
        return False

    def _computer_move(self):
        """do the computer move"""
        brain = Brain.Brain(Board.Board(), self.board.computer_token)
        self.board.makeComputerMove(brain)
        outcome = self.board.isWinner()
        if outcome == 'win':
            self._print_message('The computer has beaten you! You lose.')
            return True
        elif outcome == 'draw':
            self._print_message('The game is a tie!')
            return True
        return False

    def _print_message(self, arg):
        print arg

if __name__ == '__main__':
    g = Game()
    g.main()
