#!/usr/bin/env node
var debug = require('debug')('Tic-Tac-Toe');
var tictactoeapp = require('./tictactoeapp');
var http = require('http');
//var fs = require( 'fs' );

tictactoeapp.set('port', process.env.PORT || 8080);
tictactoeapp.set('httpsPort', process.env.PORT || 8089);

var server = tictactoeapp.listen(tictactoeapp.get('port'), function() {
  debug('Express server listening on port ' + server.address().port);
});


